apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - platform-config.yml
  - database-secret.yml
  - ticket-database.yml
  - technician-database.yml
  - ticket-service.yml
  - technician-service.yml
  - notification-service.yml
